### ISSUE TITLE
Problems using reveal.js-math in conjunction with asciidoctor

### ISSUE THREAD

**Issue by aanno** [burgerga/reveal.js-math#1]
I read about the [reveal mathjax 3 issue](https://github.com/hakimel/reveal.js/issues/2559) and decided to give your solution a try by using it for the `presentation.adoc` example of my sample project at https://github.com/aanno/ad-reveal. 

If I generate `presentation.html`, there is a sample equation on slide 3 rendered correctly.

Next step is to hack the resulting `presentation.html` with the changes you suggests in the readme (after installing `reveal.js-math` of course). However, I did not arrive at anything. I seems that rendering does not work. Certainly, I'm quite sure that your code works for you. Hence I suspect that there is some interference between `reveal.js-math` and `asciidoctor.js` that brakes the rendering.

**Comment by aanno** [comment]
According to https://docs.asciidoctor.org/asciidoctor/latest/stem/ `asciidoctor` supports MathJax 2 only. I wonder if I should expect MathJax 3 to work with it...

**Comment by burgerga** [comment]
Oof, I wouldn't know, from my short look at it, it looks like `stem` is including reveal directly which includes only the mathjax 2.
However I think that should be resolved once hakimel merges reveal.js-math into the core reveal :)
